name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  SKIP_ENV_VALIDATION: true

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Set up npm
        uses: npm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get npm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(npm store path --silent)" >> $GITHUB_ENV

      - name: Cache npm store
        uses: actions/cache@v2
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-npm-store-${{ hashFiles('**/npm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-npm-store-

      - name: Install dependencies
        run: npm install

      - name: Run typechecks
        run: npm run typecheck

      - name: Run lints
        run: npm run lint