 name: Deploy to Vercel on Merge

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: dkershner6/vercel-set-env-action@v1
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          projectName: athromic-t3
          envVariableKeys: DISCORD_CLIENT_ID,DISCORD_CLIENT_SECRET,NEXTAUTH_URL,DATABASE_URL,NEXTAUTH_SECRET,S_GITHUB_ID,S_GITHUB_SECRET
        env:
          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
          TYPE_DISCORD_CLIENT_ID: encrypted
          TARGET_DISCORD_CLIENT_ID: preview,development,production
          DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
          TYPE_DISCORD_CLIENT_SECRET: encrypted
          TARGET_DISCORD_CLIENT_SECRET: preview,development,production
          S_GITHUB_ID: ${{ secrets.S_GITHUB_ID }}
          TYPE_S_GITHUB_ID: encrypted
          TARGET_S_GITHUB_ID: preview,development,production
          S_GITHUB_SECRET: ${{ secrets.S_GITHUB_SECRET }}
          TYPE_S_GITHUB_SECRET: encrypted
          TARGET_S_GITHUB_SECRET: preview,development,production
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          TYPE_NEXTAUTH_URL: encrypted
          TARGET_NEXTAUTH_URL: preview,development,production
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TYPE_DATABASE_URL: encrypted
          TARGET_DATABASE_URL: preview,development,production
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          TYPE_NEXTAUTH_SECRET: encrypted
          TARGET_NEXTAUTH_SECRET: preview,development,production

      - uses: amondnet/vercel-action@v20
        id: vercel-deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
        env:
          VERBOSE: true
      
      - name: Debug Vercel Deployment Outputs
        run: |
          echo "Vercel Preview URL: ${{ steps.vercel-deploy.outputs.preview-url }}"
          echo "Vercel Deployment Output: ${{ toJson(steps.vercel-deploy.outputs) }}"

      - name: Ensure Success
        run: exit 0