name: Create Vercel Preview URL on Pull Request
on:
  pull_request:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      
      - uses: amondnet/vercel-action@v20
        id: vercel-deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
      
      - name: Set preview-url output
        run: |
          echo "preview-url=${{ steps.vercel-deploy.outputs.preview-url }}" >> $GITHUB_ENV
      
      - name: Add comment to pull request
        uses: actions/github-script@v4
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Deployed to [Preview URL](${ process.env.preview-url })`
            })
