name: Deploy to vercel on merge
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dkershner6/vercel-set-env-action@v1
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          projectName: athromic-t3
          envVariableKeys: DISCORD_CLIENT_ID,DISCORD_CLIENT_SECRET,NEXTAUTH_URL,DATABASE_URL,NEXTAUTH_SECRET,S_GITHUB_ID,S_GITHUB_SECRET
        env:
          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
          TYPE_DISCORD_CLIENT_ID: encrypted
          TARGET_DISCORD_CLIENT_ID: preview,development,production
          DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
          TARGET_DISCORD_CLIENT_SECRET: preview,development,production
          TYPE_DISCORD_CLIENT_SECRET: encrypted

          S_GITHUB_ID: ${{ secrets.S_GITHUB_ID }}
          TYPE_S_GITHUB_ID: encrypted
          TARGET_S_GITHUB_ID: preview,development,production

          S_GITHUB_SECRET: ${{ secrets.S_GITHUB_SECRET }}
          TYPE_S_GITHUB_SECRET: encrypted
          TARGET_S_GITHUB_SECRET: preview,development,production

          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          TARGET_NEXTAUTH_URL: preview,development,production
          TYPE_NEXTAUTH_URL: encrypted
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TARGET_DATABASE_URL: preview,development,production
          TYPE_DATABASE_URL: encrypted
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          TARGET_NEXTAUTH_SECRET: preview,development,production
          TYPE_NEXTAUTH_SECRET: encrypted
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}