name: Deploy to Vercel on Merge

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: dkershner6/vercel-set-env-action@v1
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          projectName: athromic-t3
          envVariableKeys: DISCORD_CLIENT_ID,DISCORD_CLIENT_SECRET,NEXTAUTH_URL,DATABASE_URL,NEXTAUTH_SECRET,S_GITHUB_ID,S_GITHUB_SECRET
        env:
          _GITHUB_ID: ${{ secrets._GITHUB_ID }}
          TYPE__GITHUB_ID: encrypted
          TARGET__GITHUB_ID: preview,development,production
          _GITHUB_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
          TYPE__GITHUB_SECRET: encrypted
          TARGET__GITHUB_SECRET: preview,development,production
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          TYPE_NEXTAUTH_URL: encrypted
          TARGET_NEXTAUTH_URL: preview,development,production
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TYPE_DATABASE_URL: encrypted
          TARGET_DATABASE_URL: preview,development,production
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          TYPE_NEXTAUTH_SECRET: encrypted
          TARGET_NEXTAUTH_SECRET: preview,development,production
          TURSO_CONNECTION_URL: ${{ secrets.TURSO_CONNECTION_URL }}
          TYPE_TURSO_CONNECTION_URL: encrypted
          TARGET_TURSO_CONNECTION_URL: preview,development,production
          TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
          TYPE_TURSO_AUTH_TOKEN: encrypted
          TARGET_TURSO_AUTH_TOKEN: preview,development,production

      - name: Debug Environment Variables
        run: |
          echo "_GITHUB_ID: ${{ secrets._GITHUB_ID }}"
          echo "_GITHUB_SECRET: ${{ secrets._GITHUB_SECRET }}"
          echo "NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}"
          echo "DATABASE_URL: ${{ secrets.DATABASE_URL }}"
          echo "NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}"
          echo "TURSO_CONNECTION_URL: ${{ secrets.TURSO_CONNECTION_URL }}"
          echo "TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}"

      - uses: amondnet/vercel-action@v20
        id: vercel-deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
        env:
          VERBOSE: true
      
      - name: Debug Vercel Deployment Outputs
        run: |
          echo "Vercel Preview URL: ${{ steps.vercel-deploy.outputs.preview-url }}"
          echo "Vercel Deployment Output: ${{ toJson(steps.vercel-deploy.outputs) }}"