name: Deploy to Vercel on Merge

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: dkershner6/vercel-set-env-action@v1
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          projectName: athromic-t3
          envVariableKeys: _GITHUB_ID,_GITHUB_SECRET,NEXTAUTH_URL,DATABASE_URL,NEXTAUTH_SECRET,TURSO_CONNECTION_URL,TURSO_AUTH_TOKEN,EMAIL_SERVER_USER,EMAIL_SERVER_PASSWORD,EMAIL_SERVER_HOST,EMAIL_SERVER_PORT,EMAIL_FROM,DATABASE_URI_Payload,PAYLOAD_SECRET
        env:
          _GITHUB_ID: ${{ secrets._GITHUB_ID }}
          TYPE__GITHUB_ID: encrypted
          TARGET__GITHUB_ID: preview,development,production
          _GITHUB_SECRET: ${{ secrets._GITHUB_SECRET }}
          TYPE__GITHUB_SECRET: encrypted
          TARGET__GITHUB_SECRET: preview,development,production
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          TYPE_NEXTAUTH_URL: encrypted
          TARGET_NEXTAUTH_URL: preview,development,production
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TYPE_DATABASE_URL: encrypted
          TARGET_DATABASE_URL: preview,development,production
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          TYPE_NEXTAUTH_SECRET: encrypted
          TARGET_NEXTAUTH_SECRET: preview,development,production
          TURSO_CONNECTION_URL: ${{ secrets.TURSO_CONNECTION_URL }}
          TYPE_TURSO_CONNECTION_URL: encrypted
          TARGET_TURSO_CONNECTION_URL: preview,development,production
          TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
          TYPE_TURSO_AUTH_TOKEN: encrypted
          TARGET_TURSO_AUTH_TOKEN: preview,development,production
          # Email stuff
          EMAIL_SERVER_USER: ${{ secrets.EMAIL_SERVER_USER }}
          TYPE_EMAIL_SERVER_USER: encrypted
          TARGET_EMAIL_SERVER_USER: preview,development,production
          # Password
          EMAIL_SERVER_PASSWORD: ${{ secrets.EMAIL_SERVER_PASSWORD }}
          TYPE_EMAIL_SERVER_PASSWORD: encrypted
          TARGET_EMAIL_SERVER_PASSWORD: preview,development,production
          # Host
          EMAIL_SERVER_HOST: ${{ secrets.EMAIL_SERVER_HOST }}
          TYPE_EMAIL_SERVER_HOST: encrypted
          TARGET_EMAIL_SERVER_HOST: preview,development,production
          # Port
          EMAIL_SERVER_PORT: ${{ secrets.EMAIL_SERVER_PORT }}
          TYPE_EMAIL_SERVER_PORT: encrypted
          TARGET_EMAIL_SERVER_PORT: preview,development,production
          # Email From
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          TYPE_EMAIL_FROM: encrypted
          TARGET_EMAIL_FROM: preview,development,production
          # PayloadCMS
          DATABASE_URI_Payload: ${{ secrets.DATABASE_URI_Payload }}
          TYPE_DATABASE_URI_Payload: encrypted
          TARGET_DATABASE_URI_Payload: preview,development,production
          # PayloadCMS
          PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
          TYPE_PAYLOAD_SECRET: encrypted
          TARGET_PAYLOAD_SECRET: preview,development,production

      - name: Debug Environment Variables
        run: |
          echo "_GITHUB_ID: ${{ secrets._GITHUB_ID }}"
          echo "_GITHUB_SECRET: ${{ secrets._GITHUB_SECRET }}"
          echo "NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}"
          echo "DATABASE_URL: ${{ secrets.DATABASE_URL }}"
          echo "NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}"
          echo "TURSO_CONNECTION_URL: ${{ secrets.TURSO_CONNECTION_URL }}"
          echo "TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}"
          echo "EMAIL_SERVER_USER: ${{ secrets.EMAIL_SERVER_USER }}"
          echo "EMAIL_SERVER_PASSWORD: ${{ secrets.EMAIL_SERVER_PASSWORD }}"
          echo "EMAIL_SERVER_HOST: ${{ secrets.EMAIL_SERVER_HOST }}"
          echo "EMAIL_SERVER_PORT: ${{ secrets.EMAIL_SERVER_PORT }}"
          echo "EMAIL_FROM: ${{ secrets.EMAIL_FROM }}"
          echo "DATABASE_URI_Payload: ${{ secrets.DATABASE_URI_Payload }}"
          echo "PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}"

      - uses: amondnet/vercel-action@v20
        id: vercel-deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
        env:
          VERBOSE: true
      
      - name: Debug Vercel Deployment Outputs
        run: |
          echo "Vercel Preview URL: ${{ steps.vercel-deploy.outputs.preview-url }}"
          echo "Vercel Deployment Output: ${{ toJson(steps.vercel-deploy.outputs) }}"